import type { Component } from 'vue'
import {
  Setting,
  List,
  DataLine,
  Collection,
  Document,
  FolderOpened,
  HomeFilled,
  User,
  Message,
  Bell,
  Search,
  Delete,
  Edit,
  Plus,
  Check,
  Close,
  ArrowRight,
  ArrowLeft,
  ArrowDown,
  ArrowUp,
  Download,
  Upload,
  Refresh,
  Link,
  Lock,
  Unlock,
  Star,
  StarFilled,
  Warning,
  InfoFilled,
  CircleCheck,
  CircleClose,
  Menu,
  Grid,
  PieChart,
  TrendCharts,
  Histogram,
  Opportunity,
  Histogram as BarChart,
  Suitcase,
  School,
  OfficeBuilding,
  Monitor,
  Coffee,
  Food,
  Goods,
  ShoppingCart,
  Shop,
  Wallet,
  Money,
  Coin,
  CreditCard,
  Discount,
  PriceTag,
  Ticket,
  Calendar,
  Clock,
  Timer,
  Stopwatch,
  AlarmClock,
  Position,
  MapLocation,
  Place,
  Location,
  Van,
  Bicycle,
  Ship,
  FirstAidKit,
  Umbrella,
  Phone,
  PhoneFilled,
  Message as MessageIcon,
  ChatDotRound,
  ChatLineRound,
  VideoCamera,
  Camera,
  Microphone,
  Headset,
  Mouse,
  Cpu,
  Printer,
  MagicStick,
  Picture,
  PictureFilled,
  Film,
  Reading,
  Notebook,
  DataBoard,
  Files,
  Folder,
  FolderChecked,
  FolderDelete,
  DocumentAdd,
  DocumentChecked,
  DocumentCopy,
  DocumentDelete,
  DocumentRemove,
  Trophy,
  Medal,
  TrophyBase,
  Sunny,
  Moon,
  Cloudy,
  Pouring,
  Lightning,
} from '@element-plus/icons-vue'

// 图标名称到组件的映射
const iconMap: Record<string, Component> = {
  'setting': Setting,
  'list': List,
  'dataLine': DataLine,
  'collection': Collection,
  'document': Document,
  'folderOpened': FolderOpened,
  'home': HomeFilled,
  'user': User,
  'message': Message,
  'bell': Bell,
  'search': Search,
  'delete': Delete,
  'edit': Edit,
  'plus': Plus,
  'check': Check,
  'close': Close,
  'arrowRight': ArrowRight,
  'arrowLeft': ArrowLeft,
  'arrowDown': ArrowDown,
  'arrowUp': ArrowUp,
  'download': Download,
  'upload': Upload,
  'refresh': Refresh,
  'link': Link,
  'lock': Lock,
  'unlock': Unlock,
  'star': Star,
  'starFilled': StarFilled,
  'warning': Warning,
  'info': InfoFilled,
  'circleCheck': CircleCheck,
  'circleClose': CircleClose,
  'menu': Menu,
  'grid': Grid,
  'pieChart': PieChart,
  'trendCharts': TrendCharts,
  'histogram': Histogram,
  'barChart': BarChart,
  'opportunity': Opportunity,
  'suitcase': Suitcase,
  'school': School,
  'officeBuilding': OfficeBuilding,
  'monitor': Monitor,
  'coffee': Coffee,
  'food': Food,
  'goods': Goods,
  'shoppingCart': ShoppingCart,
  'shop': Shop,
  'wallet': Wallet,
  'money': Money,
  'coin': Coin,
  'creditCard': CreditCard,
  'discount': Discount,
  'priceTag': PriceTag,
  'ticket': Ticket,
  'calendar': Calendar,
  'clock': Clock,
  'timer': Timer,
  'stopwatch': Stopwatch,
  'alarmClock': AlarmClock,
  'position': Position,
  'mapLocation': MapLocation,
  'place': Place,
  'location': Location,
  'van': Van,
  'bicycle': Bicycle,
  'ship': Ship,
  'firstAidKit': FirstAidKit,
  'umbrella': Umbrella,
  'phone': Phone,
  'phoneFilled': PhoneFilled,
  'messageIcon': MessageIcon,
  'chatDotRound': ChatDotRound,
  'chatLineRound': ChatLineRound,
  'videoCamera': VideoCamera,
  'camera': Camera,
  'microphone': Microphone,
  'headset': Headset,
  'mouse': Mouse,
  'cpu': Cpu,
  'printer': Printer,
  'magicStick': MagicStick,
  'picture': Picture,
  'pictureFilled': PictureFilled,
  'film': Film,
  'reading': Reading,
  'notebook': Notebook,
  'dataBoard': DataBoard,
  'files': Files,
  'folder': Folder,
  'folderChecked': FolderChecked,
  'folderDelete': FolderDelete,
  'documentAdd': DocumentAdd,
  'documentChecked': DocumentChecked,
  'documentCopy': DocumentCopy,
  'documentDelete': DocumentDelete,
  'documentRemove': DocumentRemove,
  'trophy': Trophy,
  'medal': Medal,
  'trophyBase': TrophyBase,
  'sunny': Sunny,
  'moon': Moon,
  'cloudy': Cloudy,
  'pouring': Pouring,
  'lightning': Lightning,
}

/**
 * 根据图标名称获取对应的 Element Plus 图标组件
 * @param iconName 图标名称
 * @returns 对应的图标组件，如果找不到则返回默认的 Document 图标
 */
export function getIconComponent(iconName: string | null | undefined): Component {
  if (!iconName) {
    return Document
  }
  return iconMap[iconName] || Document
}

/**
 * 检查图标名称是否存在于图标映射中
 * @param iconName 图标名称
 * @returns 是否存在
 */
export function hasIcon(iconName: string | null | undefined): boolean {
  if (!iconName) {
    return false
  }
  return iconName in iconMap
}

/**
 * 获取所有可用的图标名称列表
 * @returns 图标名称数组
 */
export function getIconNames(): string[] {
  return Object.keys(iconMap)
}

/**
 * 动态注册新的图标映射
 * @param name 图标名称
 * @param component 图标组件
 */
export function registerIcon(name: string, component: Component): void {
  iconMap[name] = component
}

export default {
  getIconComponent,
  hasIcon,
  getIconNames,
  registerIcon,
}
